#!/bin/bash

if [ $# -eq 0 ] 
then
    echo 'Usage: phone searchfor [...searchfor]'
    echo "(You didn't tell me what you want to search for.)"

else 
    str=""
    n=0
    for x in $@ 
    do
        if [ $n -eq 1 ]
        then
            str=$str'|' 
        fi
        str=$str$x
        n=1
    done

    egrep "$str" mydata| awk 'BEGIN {FS="|"}; {print "---------->\nname :" $1 "\naddress :" $2 "\nphone :" $3 "\n<----------" }' 
fi
